### ISSUE TITLE
Get FSR to Work

### ISSUE THREAD

**Issue by tzheng1372** [tzheng1372/bzLock#11]
- [x] connect to pi and draw schematics
- [x] write functions in bz.py
- [x] add to demo.py

**Comment by tzheng1372** [comment]
Estimated Time Left: 30 mins

**Comment by tzheng1372** [comment]
Drew schematic for connecting the FSR and amplifier to the pi.
![image](https://user-images.githubusercontent.com/96503086/219113116-11c7f559-d54c-4fb6-87f8-173cccf87ba4.png)

**Comment by peijiannuo** [comment]
need to test in demo.py
