### ISSUE TITLE
Get Load Cell to Work

### ISSUE THREAD

**Issue by tzheng1372** [tzheng1372/bzLock#13]
- [x] Research Load Cell and HX711 amplifier
- [x] connect to pi and draw schematics
- [x] write functions in bz.py
- [x] add to demo.py

**Comment by tzheng1372** [comment]
Estimated Time: 3 hours

**Comment by tzheng1372** [comment]
![image](https://user-images.githubusercontent.com/96503086/220702148-99cb27bf-d87d-4edd-914e-4e5a438151d2.png)

**Comment by peijiannuo** [comment]
need to test in demo.py

**Comment by peijiannuo** [comment]
changed to GPIO 17 and 27
