### ISSUE TITLE
Add Dummy Functions

### ISSUE THREAD

**Issue by tzheng1372** [tzheng1372/bzLock#5]
Subtasks for Dummy functions:

- [x] get input from keypad
- [x] display words on screen
- [x] reset display 
- [x] motor controls

**Comment by tzheng1372** [comment]
Added 
```
def get_weight():
def detect_phone():
```
to both fsr.py and loadcell.py

**Comment by peijiannuo** [comment]
all dummy functions going bz.py
est time half an hour

**Comment by peijiannuo** [comment]
completed adding dummy functions for the infrastructure layer
